run:
  dir: run/${scenario.domain}_${scenario.name}/${name}/${now:%Y-%m-%d_%H-%M-%S}
sweep:
  dir: multirun/${scenario.domain}_${scenario.name}/${name}/${now:%Y-%m-%d_%H-%M-%S}
  subdir: ${hydra.job.num}
job:
  env_set:
    OMP_NUM_THREADS: '1'
    XLA_PYTHON_CLIENT_PREALLOCATE: 'false'
  config:
    override_dirname:
      item_sep: /
      exclude_keys:
        - seed