name: hard
classname: scenarios.BraxScenario
domain: humanoid
tasks: ["normal","moon","carrystuff","tinyfeet"]
repeat_scenario: 1
n_train_envs: 128
n_evaluation_envs: 512
n_steps: 2_000_000
start_steps: 0
evaluate_success: False
