name: compositionality
classname: scenarios.BraxScenario
domain: ant
tasks: ["disabled_hard1","disabled_hard2","disabled_forefeet","disabled_backfeet"]
repeat_scenario: 2
n_train_envs: 128
n_evaluation_envs: 512
n_steps: 1_000_000
start_steps: 0
evaluate_success: False
