name: packnet
seed: 0

defaults: 
  - logger: wandb
  - scenario: halfcheetah/forgetting
  - hydra: hydra
  - framework/params/algorithm/generic_sac
  - framework/params/algorithm2/generic_sac
  - framework/params/policy_agent/generic_policy
  - framework/params/critic_agent/generic_critic
  - framework/params/evaluation/generic_evaluation
  - optional framework/params/evaluation: ${scenario}
  - optional framework/params/algorithm: ${scenario}
  - optional framework/params/algorithm2: ${scenario}
  - optional framework/params/policy_agent: ${scenario}
  - optional framework/params/critic_agent: ${scenario}

framework:
  classname: frameworks.TwoSteps
  seed: ${seed}
  params:
    checkpoint: False
    policy_agent:
      classname: agents.PacknetActionAgent
      prune_coeff: 0.875
