name: t6
classname: scenarios.CWScenario
domain: continual_world
tasks: [
  "stick-pull-v1",
  "peg-unplug-side-v1",
  "stick-pull-v1",
]
repeat_scenario: 1
n_train_envs: 1
n_evaluation_envs: 1
n_steps: 1_000_000
start_steps: 1_000
evaluate_success: True
